name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * 0

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "1.23.0-bookworm"
            imageTags: |
              type=raw,value=1.23.0-bookworm
              type=raw,value=1.23-bookworm
            dockerfilePath: ./1.23/bookworm/Dockerfile
            buildTarget: base
            buildArgs: |
              fromImage=golang:1.23.0-bookworm
          - name: "1.23.0-bookworm-sam"
            imageTags: |
              type=raw,value=1.23.0-bookworm-sam
              type=raw,value=1.23-bookworm-sam
            dockerfilePath: ./1.23/bookworm/Dockerfile
            buildTarget: sam
            buildArgs: |
              fromImage=golang:1.23.0-bookworm
          - name: "1.23.0-bookworm-dev"
            imageTags: |
              type=raw,value=1.23.0-bookworm-dev
              type=raw,value=1.23-bookworm-dev
            dockerfilePath: ./1.23/bookworm/Dockerfile
            buildTarget: dev
            buildArgs: |
              fromImage=golang:1.23.0-bookworm
          - name: "1.22.6-bookworm"
            imageTags: |
              type=raw,value=1.22.6-bookworm
              type=raw,value=1.22-bookworm
            dockerfilePath: ./1.22/bookworm/Dockerfile
            buildTarget: base
            buildArgs: |
              fromImage=golang:1.22.6-bookworm
          - name: "1.22.6-bookworm-sam"
            imageTags: |
              type=raw,value=1.22.6-bookworm-sam
              type=raw,value=1.22-bookworm-sam
            dockerfilePath: ./1.22/bookworm/Dockerfile
            buildTarget: sam
            buildArgs: |
              fromImage=golang:1.22.6-bookworm
          - name: "1.22.6-bookworm-dev"
            imageTags: |
              type=raw,value=1.22.6-bookworm-dev
              type=raw,value=1.22-bookworm-dev
            dockerfilePath: ./1.22/bookworm/Dockerfile
            buildTarget: dev
            buildArgs: |
              fromImage=golang:1.22.6-bookworm
          - name: "1.21.13-bookworm"
            imageTags: |
              type=raw,value=1.21.13-bookworm
              type=raw,value=1.21-bookworm
            dockerfilePath: ./1.21/bookworm/Dockerfile
            buildTarget: base
            buildArgs: |
              fromImage=golang:1.21.13-bookworm
          - name: "1.21.13-bookworm-sam"
            imageTags: |
              type=raw,value=1.21.13-bookworm-sam
              type=raw,value=1.21-bookworm-sam
            dockerfilePath: ./1.21/bookworm/Dockerfile
            buildTarget: sam
            buildArgs: |
              fromImage=golang:1.21.13-bookworm
          - name: "1.21.13-bookworm-dev"
            imageTags: |
              type=raw,value=1.21.13-bookworm-dev
              type=raw,value=1.21-bookworm-dev
            dockerfilePath: ./1.21/bookworm/Dockerfile
            buildTarget: dev
            buildArgs: |
              fromImage=golang:1.21.13-bookworm
    with:
      name: ${{ matrix.name }}
      imageRegistry: marcodellorto/golang
      imageTags: ${{ matrix.imageTags }}
      dockerfilePath: ${{ matrix.dockerfilePath }}
      buildTarget: ${{ matrix.buildTarget }}
      buildArgs: ${{ matrix.buildArgs }}
